version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_POCKETBASE_URL=${PUBLIC_POCKETBASE_URL}
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_migrations:/pb_migrations